<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYmUod4s\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYmUod4s/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYmUod4s.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYmUod4s\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYmUod4s\App_KernelDevDebugContainer([
    'container.build_hash' => 'YmUod4s',
    'container.build_id' => 'fa82586b',
    'container.build_time' => 1640722875,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYmUod4s');
