<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQqhshxs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQqhshxs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQqhshxs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQqhshxs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQqhshxs\App_KernelDevDebugContainer([
    'container.build_hash' => 'Qqhshxs',
    'container.build_id' => 'a9c9998d',
    'container.build_time' => 1639474449,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQqhshxs');
